# Generated by Django 5.1.5 on 2025-10-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status'),
        ('patient', '0016_patient_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PendingPayment', 'Pending Payment'), ('Scheduled', 'Scheduled'), ('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='PendingPayment', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('PayMaya', 'PayMaya'), ('Gcash', 'Gcash')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('paymaya_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paymaya_checkout_url', models.URLField(blank=True, null=True)),
                ('paymaya_response', models.JSONField(blank=True, null=True)),
                ('gcash_proof', models.ImageField(blank=True, null=True, upload_to='gcash_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointment.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patient.patient')),
            ],
        ),
    ]
